version: "3.8"
services:
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
  backend:
    build: ./server
    container_name: server
    ports:
      - '5000:5000'