version: "3.8"
services:
  # client:
  #   build: ./client
  #   container_name: client
  #   ports:
  #     - '3000:3000'
  # backend:
  #   build: ./server
  #   container_name: server
  #   ports:
  #     - '5000:5000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local